# Generated by Django 5.2 on 2025-04-20 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=64, verbose_name='Категориялар')),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection', models.URLField(verbose_name='Байланыш')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_pdf', models.FileField(upload_to='book_pdf', verbose_name='Китептин PDF фарматы')),
                ('book_name', models.CharField(max_length=64, verbose_name='Китептин аты')),
                ('book_author', models.CharField(max_length=64, verbose_name='Автору')),
                ('publication_year', models.CharField(max_length=32, verbose_name='Басылган жылы')),
                ('loading_time', models.DateTimeField(auto_now=True, verbose_name='Жүктөлгөн убакыт')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_app.category', verbose_name='Бөлүм')),
            ],
        ),
        migrations.CreateModel(
            name='BookLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_app.books')),
            ],
            options={
                'unique_together': {('book', 'ip_address')},
            },
        ),
    ]
