# Generated by Django 5.2 on 2025-04-20 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookLike',
        ),
    ]
