# Generated by Django 5.2 on 2025-04-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklike',
            name='unique_field',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
