# Generated by Django 5.2 on 2025-05-05 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Китеп', 'verbose_name_plural': 'Китептер'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Бөлүм', 'verbose_name_plural': 'Бөлүмдөр'},
        ),
        migrations.AlterModelOptions(
            name='connection',
            options={'verbose_name': 'Байланыш', 'verbose_name_plural': 'Байланыш'},
        ),
        migrations.AlterField(
            model_name='books',
            name='book_image',
            field=models.ImageField(blank=True, null=True, upload_to='book_images', verbose_name='Китептин суроту'),
        ),
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Түшүндүрмө'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Бөлүм'),
        ),
        migrations.AlterUniqueTogether(
            name='booklike',
            unique_together={('book', 'unique_field')},
        ),
        migrations.CreateModel(
            name='BookViewing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique', models.CharField(max_length=50, unique=True)),
                ('book_viewing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing', to='book_app.books')),
            ],
        ),
    ]
