# Generated by Django 5.2 on 2025-04-19 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_books_likes_books_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='books',
            name='views',
        ),
    ]
