# Generated by Django 5.2 on 2025-11-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_alter_books_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklike',
            name='unique_field',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
