# Generated by Django 5.2 on 2025-04-19 17:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_remove_books_likes_remove_books_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_author',
            field=models.CharField(max_length=64, verbose_name='Автору'),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_name',
            field=models.CharField(max_length=64, verbose_name='Китептер'),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_pdf',
            field=models.FileField(upload_to='book_pdf', verbose_name='Китептин PDF фарматы'),
        ),
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_app.category', verbose_name='Бөлүм'),
        ),
        migrations.AlterField(
            model_name='books',
            name='loading_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Жүктөлгөн убакыт'),
        ),
        migrations.AlterField(
            model_name='books',
            name='publication_year',
            field=models.CharField(max_length=32, verbose_name='Басылган жылы'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=64, verbose_name='Категориялар'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='connection',
            field=models.URLField(verbose_name='Байланыш'),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='purpose_text',
            field=models.TextField(verbose_name='Сайттын максаты'),
        ),
        migrations.CreateModel(
            name='BookLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('liked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='book_app.books')),
            ],
            options={
                'unique_together': {('book', 'ip_address')},
            },
        ),
    ]
