# Generated by Django 5.1.5 on 2025-04-27 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_alter_category_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_image',
            field=models.ImageField(blank=True, null=True, upload_to='book_images', verbose_name='Китептин суроту'),
        ),
        migrations.CreateModel(
            name='BookView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_field', models.CharField(max_length=50, verbose_name='Уникальный идентификатор')),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='book_app.books')),
                ('last_viewed_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_viewed', to='book_app.books')),
            ],
            options={
                'unique_together': {('unique_field', 'book')},
            },
        ),
    ]
