# Generated by Django 5.2 on 2025-04-21 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_alter_category_category_name_booklike'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_image',
            field=models.ImageField(default=1, upload_to='book_images', verbose_name='Китептин суроту'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booklike',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='book_app.books'),
        ),
    ]
