# Generated by Django 5.2 on 2025-04-27 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0004_books_view_count_alter_books_book_image_bookview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='view_count',
        ),
        migrations.DeleteModel(
            name='BookView',
        ),
    ]
