# Generated by Django 5.2 on 2025-04-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0004_alter_books_book_author_alter_books_book_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_name',
            field=models.CharField(max_length=64, verbose_name='Китептин аты'),
        ),
    ]
