# Generated by Django 5.2 on 2025-04-28 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0005_remove_books_view_count_delete_bookview'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookViewing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique', models.CharField(max_length=50, unique=True)),
                ('book_viewing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing', to='book_app.books')),
            ],
        ),
    ]
