# Generated by Django 5.2 on 2025-04-19 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0005_alter_books_book_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookLike',
        ),
    ]
