# Generated by Django 5.2 on 2025-04-20 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0006_delete_booklike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purpose',
        ),
    ]
