# Generated by Django 5.2 on 2025-04-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0006_bookviewing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Китеп', 'verbose_name_plural': 'Китептер'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Бөлүм', 'verbose_name_plural': 'Бөлүмдөр'},
        ),
        migrations.AlterModelOptions(
            name='connection',
            options={'verbose_name': 'Байланыш', 'verbose_name_plural': 'Байланыш'},
        ),
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
