# Generated by Django 5.2 on 2025-05-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0007_alter_books_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Түшүндүрмө'),
        ),
    ]
